version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
    container_name: auth-service
    ports:
      - "50053:50053"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge