version: '3.8'

services:
  auth:

    build:
      context: ./services/auth
      dockerfile: Dockerfile
    container_name: auth-service

    ports:
      - "50053:50053"

    networks:
      - microservices-net

networks:

  microservices-net:
    driver: bridge