// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: api.proto

package gateway

import (
	proto "github.com/Costin2000/GoChat---Schwarz-Internship---2025/auth/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\agateway\x1a\x1cgoogle/api/annotations.proto\x1a\x1dservices/auth/proto/api.proto2C\n" +
	"\x0eGatewayService\x121\n" +
	"\x04Ping\x12\v.auth.Empty\x1a\n" +
	".auth.Pong\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/pingBbZ`github.com/Costin2000/GoChat---Schwarz-Internship---2025/services/api-rest-gateway/proto;gatewayb\x06proto3"

var file_api_proto_goTypes = []any{
	(*proto.Empty)(nil), // 0: auth.Empty
	(*proto.Pong)(nil),  // 1: auth.Pong
}
var file_api_proto_depIdxs = []int32{
	0, // 0: gateway.GatewayService.Ping:input_type -> auth.Empty
	1, // 1: gateway.GatewayService.Ping:output_type -> auth.Pong
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
